"""Pydantic schemas for the Weekly Insight feature (v2.2)."""
from __future__ import annotations

from datetime import date
from typing import Literal, Optional

from pydantic import BaseModel


class WeeklyStats(BaseModel):
    """Computed statistics from the last 7 days of habit_logs."""

    total: int
    done: int
    snoozed: int
    skipped: int
    # Fraction of logs that were done; 0.0 when total is 0.
    completion_rate: float
    # Day-of-week name ("Monday") with the most done logs; None if no done logs.
    best_day: Optional[str] = None
    # Day-of-week name with the most skipped logs; None if no skipped logs.
    worst_day: Optional[str] = None
    # Habit name with the most done logs this week; None if no done logs.
    best_habit: Optional[str] = None
    # Habit name with the most skipped logs this week; None if no skipped logs.
    most_skipped_habit: Optional[str] = None


class WeeklyInsightResponse(BaseModel):
    """Full response returned by GET /insights/weekly."""

    week_start: date
    week_end: date
    stats: WeeklyStats
    # 2–4 sentence coaching-style summary.
    insight: str
    # "ai" when generated by OpenAI; "fallback" for deterministic or no-data responses.
    source: Literal["ai", "fallback"]
    # False when total logs < MIN_LOGS_FOR_INSIGHT; frontend uses this instead of
    # hardcoding the threshold number.
    has_enough_data: bool
